### ISSUE TITLE
Could not find sqlite3

### ISSUE THREAD

**Issue by borneq** [rust-qt/qt_widgets#1]
I try compile:

> d:\code\rust\rust-qt\qt_widgets>cargo build
>    Compiling libsqlite3-sys v0.5.0
>    Compiling rustfmt v0.6.3
> error: failed to run custom build command for `libsqlite3-sys v0.5.0`
> process didn't exit successfully: `d:\code\rust\rust-qt\qt_widgets\target\debug\build\libsqlite3-sys-3f541aaac3a27de2\build-script-build` (exit code: 101)
> --- stderr
> thread 'main' panicked at 'Could not find sqlite3. Try setting SQLITE3_LIB_DIR.', C:\Users\Andrzej Borucki\.cargo\registry\src\github.com-1ecc6299db9ec823\libsqlite3-sys-0.5.0\build.rs:19
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

is possible set SQLITE3_LIB_DIR to correct value?

**Comment by Riateche** [comment]
`cpp_to_rust` requires `sqlite3` library, so it needs to be installed somewhere in the system. For example, here is the script downloading it for Appveyor:

```
curl -o "%TEMP%\sqlite.zip" "https://www.sqlite.org/2016/sqlite-dll-win64-x64-3150100.zip" || goto :error
7z x "%TEMP%\sqlite.zip" -o"%TEMP%\sqlite" || goto :error
set SQLITE3_LIB_DIR=%TEMP%\sqlite
lib /def:%SQLITE3_LIB_DIR%\sqlite3.def /out:%SQLITE3_LIB_DIR%\sqlite3.lib || goto :error
```

You can just download a built library from [here](https://www.sqlite.org/2016/sqlite-dll-win64-x64-3150100.zip) and unpack it manually, and then run the last `lib` command to generate `.lib` file from `.def`file.
